project:
  type: website

website:
  title: "Livre d'or formation FRB-Cesab/GdR EcoStat"

  navbar:
    right:
      - href: index.qmd
        text: Page d'acceuil
      - href: commentaires.qmd
        text: Commentaires
        logo : ![](data/logo_commentaires.png)
      - href : Photos.qmd
        text : Photos
        logo : 
      - href : Video.qmd
        text : 
        logo : 
        
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: LICENSE.md
     
format:
  html:
    theme: superhero
    css: styles.css
    toc: true


editor: visual

about:
  template: jolla

