project:
  type: website

website:
  title: "Livre d'or formation FRB-Cesab/GdR EcoStat"
  navbar:
    left:
      - href: index.qmd
        text: Page d'acceuil
      - commentaires.qmd
      - Photos.qmd
     
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

