project:
  type: website

website:
  title: "Livre d'or formation FRB-Cesab/GdR EcoStat"
  image: "data/livre.png"
  page-navigation: true

  navbar:
    right:
      - href: index.qmd
      - href: commentaires.qmd
        menu: 
          - href: Photos.qmd
            text: Photos
          - href: Video.qmd
            text: Videos

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: LICENSE.md
     
format:
  html:
    theme: superhero
    css: styles.css
    toc: true


editor: visual

about:
  template: jolla

