project:
  type: website

website:
  title: "Livre d'or formation FRB-Cesab/GdR EcoStat"
  navbar:
    right:
      - href: index.qmd
      - commentaires.qmd
      - Photos.qmd
      - Video.qmd

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: LICENSE.md
     
format:
  html:
    theme: superhero
    css: styles.css
    toc: true


editor: visual

about:
  template: jolla
