project:
  type: website
  execute-dir: project

website:
  title: "Livre d'or formation FRB-Cesab/GdR EcoStat"
  page-navigation: true

  navbar:
    logo: "data/livre.png"
    right:
      - href: index.qmd
      - href: commentaires.qmd
        text: "Commentaires"
      - text: Medias
        menu: 
          - href: Photos.qmd
            text: "Photos"
          - href: Video.qmd
            text: "Videos"
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: LICENSE.md
     
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true


editor: visual

about:
  template: jolla

